ROU-4486: changes required to expand the usage of setColumnFilterOptions method
OutSystems/outsystems-datagrid pull request #383
Opened 2023-11-28 12:15 UTC by rugoncalves

This PR is not to be accepted!
It only contains the changes required to allow the action `API_Filter\SetColumnFilterOptions` to be used in more columns:
- Text
- Dropdown
- Checkbox 🌟
- Currency 🌟
- Date 🌟
- DateTime 🌟
- Number 🌟

2023-11-28 16:48 UTC, OS-giulianasilva approved these changes

2023-11-28 17:14 UTC, OS-giulianasilva requested changes
@rugoncalves I've just remembered about the Error Message that needs to be changed now that this Client Action does not work only for Text and Dropdown.

2023-11-29 11:50 UTC, JoaoFerreira-FrontEnd approved these changes

2024-01-29 22:05 UTC, gnbm commented
@rugoncalves @OS-giulianasilva I assume we can close this PR since the feature was implemented in task ROU-4659?

2024-01-30 10:14 UTC, closed without merging