ROU-4768: Fix OnCellValueChange returning the dropdown label instead of the value
OutSystems/outsystems-datagrid pull request #402
Opened 2024-03-19 14:36 UTC by OS-giulianasilva

This PR is for fixing the OnCellValueChange returning the dropdown label instead of the value

### What was happening
* When triggering the OnCellValueChange, it was returned the dropdown's formatted value (label) instead of the option id/key. 

### What was done
* In the Wijmo's getCellData method, we now set the last argument to false, this way we get the dropdown option id/key instead of the dropdown label.

### Checklist
* [x] tested locally
* [x] documented the code
* [x] clean all warnings and errors of eslint
* [] requires changes in OutSystems (if so, provide a module with changes)
* [x] requires new sample page in OutSystems (if so, provide a module with changes)

2024-03-20 11:20 UTC, joselrio approved these changes

2024-03-21 10:29 UTC, rugoncalves requested changes
These changes leave me a bit uncomfortable. The reason is that in the case of the dropdown, when the `getCellData` receives as the 3rd parameter:
   - true: it will return the label (e.g.: "_Greece_")
   - false: it will return the value (e.g.: "_5_")

So this even appears to cause a breaking change, when triggering the event... Have all situations and circumstances being analyzed?

2024-03-21 10:35 UTC, OS-giulianasilva commented
> These changes leave me a bit uncomfortable. The reason is that in the case of the dropdown, when the `getCellData` receives as the 3rd parameter:
> 
> * true: it will return the label (e.g.: "_Greece_")
> * false: it will return the value (e.g.: "_5_")
> 
> So this even appears to cause a breaking change, when triggering the event... Have all situations and circumstances been analyzed?

@rugoncalves When a dropdown is manually edited, we return the dropdown value instead of the label in the OnCellValueChange event. When the SetCellData is used, we return the label instead. So the purpose is to keep it consistent with the default behavior. 
Additionally, I performed some manual tests and ran the pipeline, and no issues were found.

2024-03-21 12:41 UTC, rugoncalves approved these changes
Consider adding additional comments in the code.

2024-03-22 17:45 UTC, merged